// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: health.proto

package healthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeScope int32

const (
	ProbeScope_PROBE_SCOPE_UNSPECIFIED ProbeScope = 0
	// One probe per attachment, sourced from that Pod's netns. Correct without
	// any topology assumption.
	ProbeScope_PROBE_SCOPE_ENDPOINT ProbeScope = 1
	// One probe per (node, NAD), shared by every attachment in the domain.
	//
	// Sharing is only sound because probe configuration -- scope, health target
	// and source interface -- is a property of the NAD and never of a Service.
	// Two Services on one NAD with different health targets would otherwise be
	// silently collapsed into one path state. Opt-in, and false for macvlan or
	// ipvlan toward same-node endpoints.
	ProbeScope_PROBE_SCOPE_NODE ProbeScope = 2
)

// Enum value maps for ProbeScope.
var (
	ProbeScope_name = map[int32]string{
		0: "PROBE_SCOPE_UNSPECIFIED",
		1: "PROBE_SCOPE_ENDPOINT",
		2: "PROBE_SCOPE_NODE",
	}
	ProbeScope_value = map[string]int32{
		"PROBE_SCOPE_UNSPECIFIED": 0,
		"PROBE_SCOPE_ENDPOINT":    1,
		"PROBE_SCOPE_NODE":        2,
	}
)

func (x ProbeScope) Enum() *ProbeScope {
	p := new(ProbeScope)
	*p = x
	return p
}

func (x ProbeScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeScope) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[0].Descriptor()
}

func (ProbeScope) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[0]
}

func (x ProbeScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeScope.Descriptor instead.
func (ProbeScope) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

// HealthEnvelope wraps every message an agent sends.
//
// Local state and path state stay separate payloads because they have different
// cardinality: local state is per attachment, always, while path state is per
// attachment under Endpoint scope and per (node, NAD) under Node scope. Merging
// them would force an agent to copy one shared Node-scope probe result into N
// per-Pod reports -- the duplication the scope exists to remove -- and give each
// copy its own hysteresis, reintroducing the transition skew that sharing is
// meant to eliminate.
type HealthEnvelope struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// agent_instance_id is fresh for every agent process. Ordering and freshness
	// must not depend on comparing a node's clock with the controller's, so the
	// instance id and the sequence number carry that responsibility instead and
	// observed_at is left purely for measurement.
	AgentInstanceId string `protobuf:"bytes,2,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"`
	// sequence increases monotonically within one instance. A gRPC stream orders
	// its own messages, but a reconnect can leave an old and a new stream briefly
	// overlapping, and the pair (instance, sequence) resolves that without a
	// clock.
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HealthEnvelope_Local
	//	*HealthEnvelope_Path
	//	*HealthEnvelope_Retired
	//	*HealthEnvelope_SnapshotBegin
	//	*HealthEnvelope_SnapshotEnd
	Payload       isHealthEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthEnvelope) Reset() {
	*x = HealthEnvelope{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEnvelope) ProtoMessage() {}

func (x *HealthEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEnvelope.ProtoReflect.Descriptor instead.
func (*HealthEnvelope) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthEnvelope) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HealthEnvelope) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *HealthEnvelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HealthEnvelope) GetPayload() isHealthEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HealthEnvelope) GetLocal() *LocalHealth {
	if x != nil {
		if x, ok := x.Payload.(*HealthEnvelope_Local); ok {
			return x.Local
		}
	}
	return nil
}

func (x *HealthEnvelope) GetPath() *PathHealth {
	if x != nil {
		if x, ok := x.Payload.(*HealthEnvelope_Path); ok {
			return x.Path
		}
	}
	return nil
}

func (x *HealthEnvelope) GetRetired() *AttachmentRetired {
	if x != nil {
		if x, ok := x.Payload.(*HealthEnvelope_Retired); ok {
			return x.Retired
		}
	}
	return nil
}

func (x *HealthEnvelope) GetSnapshotBegin() *SnapshotBegin {
	if x != nil {
		if x, ok := x.Payload.(*HealthEnvelope_SnapshotBegin); ok {
			return x.SnapshotBegin
		}
	}
	return nil
}

func (x *HealthEnvelope) GetSnapshotEnd() *SnapshotEnd {
	if x != nil {
		if x, ok := x.Payload.(*HealthEnvelope_SnapshotEnd); ok {
			return x.SnapshotEnd
		}
	}
	return nil
}

type isHealthEnvelope_Payload interface {
	isHealthEnvelope_Payload()
}

type HealthEnvelope_Local struct {
	Local *LocalHealth `protobuf:"bytes,10,opt,name=local,proto3,oneof"`
}

type HealthEnvelope_Path struct {
	Path *PathHealth `protobuf:"bytes,11,opt,name=path,proto3,oneof"`
}

type HealthEnvelope_Retired struct {
	Retired *AttachmentRetired `protobuf:"bytes,12,opt,name=retired,proto3,oneof"`
}

type HealthEnvelope_SnapshotBegin struct {
	SnapshotBegin *SnapshotBegin `protobuf:"bytes,13,opt,name=snapshot_begin,json=snapshotBegin,proto3,oneof"`
}

type HealthEnvelope_SnapshotEnd struct {
	SnapshotEnd *SnapshotEnd `protobuf:"bytes,14,opt,name=snapshot_end,json=snapshotEnd,proto3,oneof"`
}

func (*HealthEnvelope_Local) isHealthEnvelope_Payload() {}

func (*HealthEnvelope_Path) isHealthEnvelope_Payload() {}

func (*HealthEnvelope_Retired) isHealthEnvelope_Payload() {}

func (*HealthEnvelope_SnapshotBegin) isHealthEnvelope_Payload() {}

func (*HealthEnvelope_SnapshotEnd) isHealthEnvelope_Payload() {}

// SnapshotBegin opens an atomic replacement of everything the controller holds
// for this node.
//
// Without it, a controller that restarted while an agent was mid-send would
// reconcile against a partial set and briefly publish the rest as not ready.
// The controller buffers until SnapshotEnd and commits in one step.
type SnapshotBegin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// expected_local and expected_path let the controller notice a truncated
	// snapshot instead of committing it.
	ExpectedLocal uint32 `protobuf:"varint,2,opt,name=expected_local,json=expectedLocal,proto3" json:"expected_local,omitempty"`
	ExpectedPath  uint32 `protobuf:"varint,3,opt,name=expected_path,json=expectedPath,proto3" json:"expected_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotBegin) Reset() {
	*x = SnapshotBegin{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotBegin) ProtoMessage() {}

func (x *SnapshotBegin) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotBegin.ProtoReflect.Descriptor instead.
func (*SnapshotBegin) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotBegin) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SnapshotBegin) GetExpectedLocal() uint32 {
	if x != nil {
		return x.ExpectedLocal
	}
	return 0
}

func (x *SnapshotBegin) GetExpectedPath() uint32 {
	if x != nil {
		return x.ExpectedPath
	}
	return 0
}

type SnapshotEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnd) Reset() {
	*x = SnapshotEnd{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnd) ProtoMessage() {}

func (x *SnapshotEnd) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnd.ProtoReflect.Descriptor instead.
func (*SnapshotEnd) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotEnd) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// LocalHealth is one attachment's interface state, observed from inside its Pod
// netns. It is not observable from the host netns: macvlan and ipvlan move the
// child device wholly into the Pod namespace.
type LocalHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// attachment_id is hash(pod_uid | nad | interface_name | ip), recomputed by
	// the controller from the current network-status. A report whose id does not
	// match a known attachment is rejected, which is what stops a report that was
	// in flight across a sandbox recreate from landing on the new attachment.
	AttachmentId  string `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	PodUid        string `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Nad           string `protobuf:"bytes,5,opt,name=nad,proto3" json:"nad,omitempty"`                                          // canonical "ns/name"
	InterfaceName string `protobuf:"bytes,6,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"` // from network-status, never assumed to be net1
	Ip            string `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	LocalReady    bool   `protobuf:"varint,8,opt,name=local_ready,json=localReady,proto3" json:"local_ready,omitempty"`
	// The three checks are reported individually because they fail differently.
	// Taking a link down leaves the IPv4 address in place, so address_present
	// alone reports a dead interface as healthy.
	InterfaceExists bool `protobuf:"varint,9,opt,name=interface_exists,json=interfaceExists,proto3" json:"interface_exists,omitempty"`
	AddressPresent  bool `protobuf:"varint,10,opt,name=address_present,json=addressPresent,proto3" json:"address_present,omitempty"`
	LinkUsable      bool `protobuf:"varint,11,opt,name=link_usable,json=linkUsable,proto3" json:"link_usable,omitempty"`
	// observed_at is for measurement only. Freshness is judged from when the
	// controller accepted the report, so a skewed node clock cannot make a stale
	// report look current or a current one look stale.
	ObservedAtUnixNano int64 `protobuf:"varint,12,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LocalHealth) Reset() {
	*x = LocalHealth{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalHealth) ProtoMessage() {}

func (x *LocalHealth) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalHealth.ProtoReflect.Descriptor instead.
func (*LocalHealth) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *LocalHealth) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *LocalHealth) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *LocalHealth) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LocalHealth) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *LocalHealth) GetNad() string {
	if x != nil {
		return x.Nad
	}
	return ""
}

func (x *LocalHealth) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *LocalHealth) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LocalHealth) GetLocalReady() bool {
	if x != nil {
		return x.LocalReady
	}
	return false
}

func (x *LocalHealth) GetInterfaceExists() bool {
	if x != nil {
		return x.InterfaceExists
	}
	return false
}

func (x *LocalHealth) GetAddressPresent() bool {
	if x != nil {
		return x.AddressPresent
	}
	return false
}

func (x *LocalHealth) GetLinkUsable() bool {
	if x != nil {
		return x.LinkUsable
	}
	return false
}

func (x *LocalHealth) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

// PathHealth is an active probe result. netlink cannot supply it: an underlay
// blackhole breaks reachability while changing no local kernel state at all.
type PathHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope ProbeScope             `protobuf:"varint,1,opt,name=scope,proto3,enum=secondaryservice.v1.ProbeScope" json:"scope,omitempty"`
	// scope_id is the attachment_id under Endpoint scope and
	// hash(node_name | nad) under Node scope. The controller joins on it, so one
	// Node-scope report serves every attachment in the domain without being
	// copied per Pod.
	ScopeId string `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Nad     string `protobuf:"bytes,3,opt,name=nad,proto3" json:"nad,omitempty"`
	Target  string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// path_ready is post-hysteresis. The raw counters stay on the agent so a
	// shared domain has exactly one hysteresis state rather than one per
	// attachment.
	PathReady          bool  `protobuf:"varint,5,opt,name=path_ready,json=pathReady,proto3" json:"path_ready,omitempty"`
	ObservedAtUnixNano int64 `protobuf:"varint,6,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PathHealth) Reset() {
	*x = PathHealth{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathHealth) ProtoMessage() {}

func (x *PathHealth) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathHealth.ProtoReflect.Descriptor instead.
func (*PathHealth) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *PathHealth) GetScope() ProbeScope {
	if x != nil {
		return x.Scope
	}
	return ProbeScope_PROBE_SCOPE_UNSPECIFIED
}

func (x *PathHealth) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *PathHealth) GetNad() string {
	if x != nil {
		return x.Nad
	}
	return ""
}

func (x *PathHealth) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PathHealth) GetPathReady() bool {
	if x != nil {
		return x.PathReady
	}
	return false
}

func (x *PathHealth) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

// AttachmentRetired says an attachment is gone. Snapshots would eventually
// remove it anyway; sending it immediately closes the window in which a stale
// entry could still be read.
type AttachmentRetired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentRetired) Reset() {
	*x = AttachmentRetired{}
	mi := &file_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentRetired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentRetired) ProtoMessage() {}

func (x *AttachmentRetired) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentRetired.ProtoReflect.Descriptor instead.
func (*AttachmentRetired) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{5}
}

func (x *AttachmentRetired) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

type HealthAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted_sequence is the highest sequence the controller has processed.
	AcceptedSequence uint64 `protobuf:"varint,1,opt,name=accepted_sequence,json=acceptedSequence,proto3" json:"accepted_sequence,omitempty"`
	// resync_required asks the agent to send a full snapshot, e.g. after a
	// controller restart or when a report arrived for an unknown subject.
	ResyncRequired bool   `protobuf:"varint,2,opt,name=resync_required,json=resyncRequired,proto3" json:"resync_required,omitempty"`
	Reason         string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthAck) Reset() {
	*x = HealthAck{}
	mi := &file_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAck) ProtoMessage() {}

func (x *HealthAck) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAck.ProtoReflect.Descriptor instead.
func (*HealthAck) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{6}
}

func (x *HealthAck) GetAcceptedSequence() uint64 {
	if x != nil {
		return x.AcceptedSequence
	}
	return 0
}

func (x *HealthAck) GetResyncRequired() bool {
	if x != nil {
		return x.ResyncRequired
	}
	return false
}

func (x *HealthAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x13secondaryservice.v1\"\xc9\x03\n" +
	"\x0eHealthEnvelope\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12*\n" +
	"\x11agent_instance_id\x18\x02 \x01(\tR\x0fagentInstanceId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x128\n" +
	"\x05local\x18\n" +
	" \x01(\v2 .secondaryservice.v1.LocalHealthH\x00R\x05local\x125\n" +
	"\x04path\x18\v \x01(\v2\x1f.secondaryservice.v1.PathHealthH\x00R\x04path\x12B\n" +
	"\aretired\x18\f \x01(\v2&.secondaryservice.v1.AttachmentRetiredH\x00R\aretired\x12K\n" +
	"\x0esnapshot_begin\x18\r \x01(\v2\".secondaryservice.v1.SnapshotBeginH\x00R\rsnapshotBegin\x12E\n" +
	"\fsnapshot_end\x18\x0e \x01(\v2 .secondaryservice.v1.SnapshotEndH\x00R\vsnapshotEndB\t\n" +
	"\apayload\"q\n" +
	"\rSnapshotBegin\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12%\n" +
	"\x0eexpected_local\x18\x02 \x01(\rR\rexpectedLocal\x12#\n" +
	"\rexpected_path\x18\x03 \x01(\rR\fexpectedPath\"#\n" +
	"\vSnapshotEnd\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\"\x96\x03\n" +
	"\vLocalHealth\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12\x10\n" +
	"\x03nad\x18\x05 \x01(\tR\x03nad\x12%\n" +
	"\x0einterface_name\x18\x06 \x01(\tR\rinterfaceName\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x1f\n" +
	"\vlocal_ready\x18\b \x01(\bR\n" +
	"localReady\x12)\n" +
	"\x10interface_exists\x18\t \x01(\bR\x0finterfaceExists\x12'\n" +
	"\x0faddress_present\x18\n" +
	" \x01(\bR\x0eaddressPresent\x12\x1f\n" +
	"\vlink_usable\x18\v \x01(\bR\n" +
	"linkUsable\x121\n" +
	"\x15observed_at_unix_nano\x18\f \x01(\x03R\x12observedAtUnixNano\"\xda\x01\n" +
	"\n" +
	"PathHealth\x125\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x1f.secondaryservice.v1.ProbeScopeR\x05scope\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x10\n" +
	"\x03nad\x18\x03 \x01(\tR\x03nad\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"path_ready\x18\x05 \x01(\bR\tpathReady\x121\n" +
	"\x15observed_at_unix_nano\x18\x06 \x01(\x03R\x12observedAtUnixNano\"8\n" +
	"\x11AttachmentRetired\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\"y\n" +
	"\tHealthAck\x12+\n" +
	"\x11accepted_sequence\x18\x01 \x01(\x04R\x10acceptedSequence\x12'\n" +
	"\x0fresync_required\x18\x02 \x01(\bR\x0eresyncRequired\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*Y\n" +
	"\n" +
	"ProbeScope\x12\x1b\n" +
	"\x17PROBE_SCOPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROBE_SCOPE_ENDPOINT\x10\x01\x12\x14\n" +
	"\x10PROBE_SCOPE_NODE\x10\x022a\n" +
	"\x0eHealthReporter\x12O\n" +
	"\x04Sync\x12#.secondaryservice.v1.HealthEnvelope\x1a\x1e.secondaryservice.v1.HealthAck(\x010\x01B0Z.github.com/boanlab/multus-service/api/healthpbb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_health_proto_goTypes = []any{
	(ProbeScope)(0),           // 0: secondaryservice.v1.ProbeScope
	(*HealthEnvelope)(nil),    // 1: secondaryservice.v1.HealthEnvelope
	(*SnapshotBegin)(nil),     // 2: secondaryservice.v1.SnapshotBegin
	(*SnapshotEnd)(nil),       // 3: secondaryservice.v1.SnapshotEnd
	(*LocalHealth)(nil),       // 4: secondaryservice.v1.LocalHealth
	(*PathHealth)(nil),        // 5: secondaryservice.v1.PathHealth
	(*AttachmentRetired)(nil), // 6: secondaryservice.v1.AttachmentRetired
	(*HealthAck)(nil),         // 7: secondaryservice.v1.HealthAck
}
var file_health_proto_depIdxs = []int32{
	4, // 0: secondaryservice.v1.HealthEnvelope.local:type_name -> secondaryservice.v1.LocalHealth
	5, // 1: secondaryservice.v1.HealthEnvelope.path:type_name -> secondaryservice.v1.PathHealth
	6, // 2: secondaryservice.v1.HealthEnvelope.retired:type_name -> secondaryservice.v1.AttachmentRetired
	2, // 3: secondaryservice.v1.HealthEnvelope.snapshot_begin:type_name -> secondaryservice.v1.SnapshotBegin
	3, // 4: secondaryservice.v1.HealthEnvelope.snapshot_end:type_name -> secondaryservice.v1.SnapshotEnd
	0, // 5: secondaryservice.v1.PathHealth.scope:type_name -> secondaryservice.v1.ProbeScope
	1, // 6: secondaryservice.v1.HealthReporter.Sync:input_type -> secondaryservice.v1.HealthEnvelope
	7, // 7: secondaryservice.v1.HealthReporter.Sync:output_type -> secondaryservice.v1.HealthAck
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	file_health_proto_msgTypes[0].OneofWrappers = []any{
		(*HealthEnvelope_Local)(nil),
		(*HealthEnvelope_Path)(nil),
		(*HealthEnvelope_Retired)(nil),
		(*HealthEnvelope_SnapshotBegin)(nil),
		(*HealthEnvelope_SnapshotEnd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		EnumInfos:         file_health_proto_enumTypes,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
