// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: health.proto

package healthpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthReporter_Sync_FullMethodName = "/secondaryservice.v1.HealthReporter/Sync"
)

// HealthReporterClient is the client API for HealthReporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HealthReporter carries network observations from the node agents to the
// controller. The agents measure; the controller decides.
//
// Two invariants shape this protocol.
//
// First, an agent report is not a discovery authority. The controller derives
// the attachment set from Service + Pod + network-status and computes the
// attachment id itself; a report can only update the health of something the
// controller already knows about. A report naming an unknown attachment is
// rejected, never used to create one.
//
// Second, health state is a renewable lease, not an event log. An agent that
// only spoke on change would go silent after a controller restart -- the state
// would still be healthy, so nothing would change, and every endpoint would sit
// at Unknown forever. Agents therefore resend a full snapshot on every connect
// and refresh periodically.
type HealthReporterClient interface {
	// Sync is bidirectional so the controller can ask for a resync without the
	// agent having to poll for permission. The reverse direction carries nothing
	// else: this is a health transport, not a control protocol.
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HealthEnvelope, HealthAck], error)
}

type healthReporterClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthReporterClient(cc grpc.ClientConnInterface) HealthReporterClient {
	return &healthReporterClient{cc}
}

func (c *healthReporterClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HealthEnvelope, HealthAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthReporter_ServiceDesc.Streams[0], HealthReporter_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HealthEnvelope, HealthAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthReporter_SyncClient = grpc.BidiStreamingClient[HealthEnvelope, HealthAck]

// HealthReporterServer is the server API for HealthReporter service.
// All implementations must embed UnimplementedHealthReporterServer
// for forward compatibility.
//
// HealthReporter carries network observations from the node agents to the
// controller. The agents measure; the controller decides.
//
// Two invariants shape this protocol.
//
// First, an agent report is not a discovery authority. The controller derives
// the attachment set from Service + Pod + network-status and computes the
// attachment id itself; a report can only update the health of something the
// controller already knows about. A report naming an unknown attachment is
// rejected, never used to create one.
//
// Second, health state is a renewable lease, not an event log. An agent that
// only spoke on change would go silent after a controller restart -- the state
// would still be healthy, so nothing would change, and every endpoint would sit
// at Unknown forever. Agents therefore resend a full snapshot on every connect
// and refresh periodically.
type HealthReporterServer interface {
	// Sync is bidirectional so the controller can ask for a resync without the
	// agent having to poll for permission. The reverse direction carries nothing
	// else: this is a health transport, not a control protocol.
	Sync(grpc.BidiStreamingServer[HealthEnvelope, HealthAck]) error
	mustEmbedUnimplementedHealthReporterServer()
}

// UnimplementedHealthReporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthReporterServer struct{}

func (UnimplementedHealthReporterServer) Sync(grpc.BidiStreamingServer[HealthEnvelope, HealthAck]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedHealthReporterServer) mustEmbedUnimplementedHealthReporterServer() {}
func (UnimplementedHealthReporterServer) testEmbeddedByValue()                        {}

// UnsafeHealthReporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthReporterServer will
// result in compilation errors.
type UnsafeHealthReporterServer interface {
	mustEmbedUnimplementedHealthReporterServer()
}

func RegisterHealthReporterServer(s grpc.ServiceRegistrar, srv HealthReporterServer) {
	// If the following call panics, it indicates UnimplementedHealthReporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthReporter_ServiceDesc, srv)
}

func _HealthReporter_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthReporterServer).Sync(&grpc.GenericServerStream[HealthEnvelope, HealthAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthReporter_SyncServer = grpc.BidiStreamingServer[HealthEnvelope, HealthAck]

// HealthReporter_ServiceDesc is the grpc.ServiceDesc for HealthReporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthReporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secondaryservice.v1.HealthReporter",
	HandlerType: (*HealthReporterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _HealthReporter_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "health.proto",
}
